# Generated by Django 4.2.2 on 2023-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersApartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('region', models.IntegerField()),
                ('level', models.IntegerField()),
                ('levels', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('kitchen_area', models.FloatField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
